version: '3.7'
services:
  web:
    tty: true
    image: wordpress
    container_name: web
    depends_on:
      - database
    ports:
      - 9045:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: user_bd
  database:
    tty: true
    image: mysql/mysql-server:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_bd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  ansible:
    tty: true
    image: ansible
    container_name: ansible
    depends_on:
      - database
      - web
    

    
